### ISSUE TITLE
Resulting file has small gap at start

### ISSUE THREAD

**Issue by joeldarling** [YYUUGGOO/repitch#1] opened 2024-05-23 20:06 UTC
Hey there, 

Thanks again for this awesome tool! 

I noticed in a few of my initial attempts, the resulting file has a small gap at the start of the file, enough to throw off a loop's timing once import to the KOii.. not sure if there's a rounding error somewhere that's causing it? 

Easy enough to re-import to editor to trim, or to trim on ko ii, but wanted to mention. 

Ex:

Original:
<img width="460" alt="image" src="https://github.com/YYUUGGOO/repitch/assets/11351753/a8da8561-2f34-4225-8dc6-95aabbf01a0f">

Result:
<img width="412" alt="image" src="https://github.com/YYUUGGOO/repitch/assets/11351753/3181513e-af56-4eb7-8206-94da800a9668">

**Comment by YYUUGGOO** [comment] 2024-05-25 05:39
Thanks for opening an issue!

I have looked into this and solving the issue isn't trivial. I have found out that WebAudio Buffers are prone to latency problems in general. That's why we usually don't have gapless playback in the browser (e.g. Spotify). I'll have to rewrite the site and do the conversion server side but that will take some time.

**Comment by YYUUGGOO** [comment] 2024-05-27 04:12
The issue has been fixed with the newest update. The tool does not encode to MP3 anymore though. Now the raw PCMBuffer is being encoded to WAV instead.

**Closed as completed by YYUUGGOO** 2024-05-27 04:12 UTC

**Comment by joeldarling** [comment] 2024-05-30 02:23
Amazing! WAV is probably preferable, for me anyways. Thanks for looking at it, love the tool :D

**Comment by joeldarling** [comment] 2024-05-30 02:33
Actually, looks like mono doesn't work now. Ah well.

**Comment by YYUUGGOO** [comment] 2024-05-30 02:45
> Actually, looks like mono doesn't work now. Ah well.

can you tell me how to reproduce that? i just tried various options and mono works for me. What browser are you using?

**Comment by joeldarling** [comment] 2024-05-30 14:24
Sure! I'm using Chrome. I drug in a WAV file with MONO enabled. I see console output for file stats, but no file actually downloads. Ad Blocker disabled..

**Comment by joeldarling** [comment] 2024-05-30 14:26
Agh... you know what it is? My source WAV file was already MONO. I had generated using this site: https://aisamplegenerator.com/, and didn't realize it was saving in mono

**Comment by YYUUGGOO** [comment] 2024-05-31 03:07
> Agh... you know what it is? My source WAV file was already MONO. I had generated using this site: https://aisamplegenerator.com/, and didn't realize it was saving in mono

glad you sorted it out! :)
